server {
    listen 80;
    server_name localhost;
    client_max_body_size 8M;

    # Directorio donde se sirven los archivos estáticos de Vite
    root /usr/share/nginx/html;
    index index.html;

    # Gestión del enrutamiento de la Single Page Application (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # =========================================================
    # ENFOQUE DE SERVICIOS DISTRIBUIDOS (Reverse Proxy)
    # Redirección de peticiones del frontend a backend Node.js
    # =========================================================
    location /api/ {
        # 'mercadoliebre_api' o el nombre del servicio internamente (mercadoliebre_api es container_name)
        # usaremos el nombre del servicio de docker compose: api-service en puerto 3000
        proxy_pass http://api-service:3000/api/;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;

        # Opcional: headers para CORS si el microservicio lo requiere
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'X-Requested-With,Accept,Content-Type, Origin';
    }
}
